spring:
  application:
    name: shop
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:shop
jwt:
  secret: 1557d8faff811e640e8f15480ef8343f09f0ebdd4e8ecfa67a089f453ef46dcb

