spring:
  application:
    name: shop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        #  show_sql: true
#        format_sql: true
#        use_sql_comments: true

jwt:
  secret:
    key: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
