spring:
  application:
    name: shop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:
    hikari:
      maximum-pool-size: 10       # 최대 커넥션 풀 크기
      minimum-idle: 2            # 최소 유휴 커넥션 수
      connection-timeout: 20000  # 커넥션 대기 타임아웃 (밀리초)
  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
        format_sql: true

jwt:
  secret:
    key: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
