spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: doit
    password:
  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 시작 시 DB 스키마 자동 생성
    show-sql: true # 실행되는 SQL 로그 출력
  h2:
    console:
      enabled: true # H2 콘솔 활성화

  application:
    name: shop

server :
  port: 8080