server:
  servlet:
    context-path: /
spring:
  application:
    name: shop
  jwt:
    secret: dGhpcy1pcy1qd3Qtc2VjcmV0LXJhdy12YWx1ZS1mb3ItbnVkZ2Utd2l0dC1iYWNrZW5kLWF1dGgtd2l0aC1qd3QtdG9rZW4tdGhpcy1pcy1qd3Qtc2VjcmV0LXJhdy12YWx1ZS1mb3ItbnVkZ2Utd2l0dC1iYWNrZW5kLWF1dGgtd2l0aC1qd3QtdG9rZW4=
    access-token-expiration: 5184000000  # 60d
    refresh-token-expiration: 15552000000 # 180d
  datasource:
    url: jdbc:mariadb://localhost:3306/shop
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
